version: '2'

services:
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/html
    ports:
      - '80:80'
    depends_on:
      - db
    group_add:
      - www-data
  db:
    build: ./docker/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
#    volumes:
#      - ./sql:/docker-entrypoint-initdb.d