<form class="editTicketForm">
    <input type="hidden" name="id">
    <div class="form-group">
        <label for="ticketTitle">Title</label>
        <input type="text" class="form-control" id="ticketTitle" placeholder="Enter ticket title" name="title" required>
    </div>
    <div class="form-group">
        <label for="ticketText">Text</label>
        <textarea class="form-control" id="ticketText" placeholder="Enter ticket text" name="text" required></textarea>
    </div>
    <div class="form-group">
        <label for="ticketDate">Date</label>
        <input type="date" class="form-control" id="ticketDate" placeholder="YYYY-MM-DD" data-date-split-input="true" name="date" required mi>
    </div>
    <div class="form-group">
        <label for="ticketDate">Status</label>
        <select class="custom-select" name="status">
            <option selected value="new">New</option>
            <option value="in action">In action</option>
            <option value="done">Done</option>
        </select>
    </div>
    <button type="button" class="btn btn-primary saveTicket">Submit</button>
</form>
